"""
faiss_indexer.py — FAISS-indexed Latent Space Novelty Monitor

At probe time, we run the XGBoost model in "predict leaf" mode, which returns
the decision tree leaf index each sample ends up in. This leaf path is the
model's learned "latent fingerprint" of that data point. We index all probe
samples (generated by LHS) into a FAISS flat L2 index.

At inference time, we extract the new data point's leaf path and query the
FAISS index for its k-nearest neighbors. If the average distance exceeds the
95th-percentile distance seen during probing, the point is in uncharted
territory — the model is extrapolating, not interpolating — and we flag it
as LATENT_NOVELTY.
"""
import logging
import numpy as np
from dataclasses import dataclass, field
from typing import Optional

import faiss

logger = logging.getLogger(__name__)


@dataclass
class NoveltyResult:
    """Result returned by a single novelty check."""
    is_novel: bool
    distance: float
    threshold: float
    novelty_score: float  # normalized 0.0–1.0+ (>1.0 means beyond threshold)


class FAISSNoveltyIndexer:
    """
    Builds and queries a FAISS flat L2 index over XGBoost leaf-path vectors.

    Leaf paths encode the model's internal representation of a data point:
    each tree votes on which leaf the point belongs to, creating a high-
    dimensional categorical fingerprint. L2 distance in this space naturally
    captures behavioral novelty.
    """

    def __init__(self, n_neighbors: int = 5, margin: float = 2.0):
        self.n_neighbors = n_neighbors
        self.margin = margin
        self._index: Optional[faiss.IndexFlatL2] = None
        self._threshold: Optional[float] = None
        self._probe_leaf_matrix: Optional[np.ndarray] = None
        self._is_built: bool = False

    @property
    def is_built(self) -> bool:
        return self._is_built

    @property
    def threshold(self) -> Optional[float]:
        return self._threshold

    def build(self, model, probe_X: np.ndarray) -> None:
        """
        Index the probe samples' leaf paths.

        Args:
            model: An xgb.Booster with a trained survival:aft model.
            probe_X: np.ndarray of shape (n_probe, n_features) — the LHS probe samples.
        """
        import xgboost as xgb

        logger.info("FAISSNoveltyIndexer: extracting leaf paths from %d probe samples...", len(probe_X))
        dmatrix = xgb.DMatrix(probe_X.astype(np.float32))

        # predict_leaf returns shape (n_samples, n_trees), dtype int32
        leaf_paths = model.predict(dmatrix, pred_leaf=True).astype(np.float32)
        self._probe_leaf_matrix = leaf_paths

        dim = leaf_paths.shape[1]
        self._index = faiss.IndexFlatL2(dim)
        self._index.add(leaf_paths)

        # Calibrate threshold: compute pairwise distances for a sample of probes
        k = min(self.n_neighbors + 1, len(leaf_paths))
        distances, _ = self._index.search(leaf_paths, k)
        # Take the mean of the k-nearest (exclude self, index 0)
        mean_distances = distances[:, 1:].mean(axis=1)
        
        # LHS is highly sparse in 5D. To avoid flagging normal but un-sampled areas 
        # (like [0,0,0,0,0]) as novel, we use the maximum probe distance * margin.
        base_max_dist = float(np.max(mean_distances))
        self._threshold = base_max_dist * self.margin
        self._is_built = True

        logger.info(
            "FAISSNoveltyIndexer: index built. dim=%d, n_probe=%d, threshold(max*%.1f)=%.4f",
            dim, len(leaf_paths), self.margin, self._threshold
        )

    def score(self, model, X: np.ndarray) -> NoveltyResult:
        """
        Score a single inference sample for latent novelty.

        Args:
            model: An xgb.Booster.
            X: np.ndarray of shape (1, n_features).

        Returns:
            NoveltyResult with distance, threshold, and novelty flag.
        """
        if not self._is_built:
            raise RuntimeError("FAISSNoveltyIndexer.build() must be called before scoring.")

        import xgboost as xgb

        dmatrix = xgb.DMatrix(X.astype(np.float32))
        leaf_path = model.predict(dmatrix, pred_leaf=True).astype(np.float32)

        k = min(self.n_neighbors, self._index.ntotal)
        distances, _ = self._index.search(leaf_path, k)
        mean_dist = float(distances[0].mean())

        novelty_score = mean_dist / self._threshold if self._threshold > 0 else 0.0
        is_novel = mean_dist > self._threshold

        return NoveltyResult(
            is_novel=is_novel,
            distance=mean_dist,
            threshold=self._threshold,
            novelty_score=round(novelty_score, 4)
        )

    def score_batch(self, model, X: np.ndarray) -> list[NoveltyResult]:
        """Score a batch of inference samples."""
        if not self._is_built:
            raise RuntimeError("FAISSNoveltyIndexer.build() must be called before scoring.")

        import xgboost as xgb

        dmatrix = xgb.DMatrix(X.astype(np.float32))
        leaf_paths = model.predict(dmatrix, pred_leaf=True).astype(np.float32)

        k = min(self.n_neighbors, self._index.ntotal)
        distances, _ = self._index.search(leaf_paths, k)
        mean_distances = distances.mean(axis=1)

        results = []
        for dist in mean_distances:
            novelty_score = float(dist) / self._threshold if self._threshold > 0 else 0.0
            results.append(NoveltyResult(
                is_novel=float(dist) > self._threshold,
                distance=float(dist),
                threshold=self._threshold,
                novelty_score=round(novelty_score, 4)
            ))
        return results
